[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rs|rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
shebangs = ["rust-script", "cargo"]
auto-format = true
comment-tokens = ["//", "///", "//!"]
block-comment-tokens = [
  { start = "/*", end = "*/" },
  { start = "/**", end = "*/" },
  { start = "/*!", end = "*/" },
]
language-servers = ["rust-analyzer", "harper-ls"]
indent = { tab-width = 4, unit = "    " }
persistent-diagnostic-sources = ["rustc", "clippy"]
formatter = { command = "rustfmt" }

[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[[language]]
name = "python"
language-servers = ["ty", "ruff", "codebook", "harper-ls"]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.rumdl]
command = "rumdl"
args = ["server"]

[[language]]
name = "yaml"
auto-format = true
language-servers = ["yaml-language-server", "codebook"]
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[[language]]
name = "toml"
auto-format = true
language-servers = ["codebook", "harper-ls"]
formatter = { command = "taplo", args = ["format", "-"] }

[[language]]
name = "json"
language-servers = ["codebook"]
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "markdown"
auto-format = true
language-servers = ["harper-ls", "marksman", "rumdl"]
soft-wrap.enable = true
text-width = 120
soft-wrap.wrap-at-text-width = true

[language-server.gopls.config]
gofumpt = true
