#!/usr/bin/env zsh
alias gitlab-pipelines="$HOME/.config/scripts/gitlab-project --host $GITLAB_HOST"
alias gitlab-merge-requests="$HOME/.config/scripts/gitlab-project --host $GITLAB_HOST --mr"
alias glp="gitlab-pipelines"
alias glmr="gitlab-merge-requests"
