#!/usr/bin/env zsh

# Aliases
alias edit-zsh-config="code $ZDOTDIR/.zshrc"
alias reload-zsh-config="source $ZDOTDIR/.zshrc"
alias start-remote-browser='docker run --rm -d -p 4444:4444 -p 7900:7900 --name remote-browser --shm-size="2g" -e SCREEN_WIDTH="1280" -e SCREEN_HEIGHT="720" selenium/standalone-chrome:4.1.1-20220121'
alias restart-remote-browser='docker restart remote-browser'
alias stop-remote-browser='docker stop remote-browser'
alias start-remote-browser-debug='docker run --rm -d -p 4444:4444 -p 7900:7900 --name remote-browser-debug --shm-size="2g" -e SCREEN_WIDTH="1280" -e SCREEN_HEIGHT="720" -e SE_OPTS="--log-level FINE" selenium/standalone-chrome:4.1.1-20220121'
alias restart-remote-browser-debug='docker restart remote-browser-debug'
alias stop-remote-browser-debug='docker stop remote-browser-debug'
alias vpn-start="sudo systemctl start $VPN_PROFILE_NAME"
alias vpn-stop="sudo systemctl stop $VPN_PROFILE_NAME"
alias vpn-status="sudo systemctl status $VPN_PROFILE_NAME"
alias portainer="docker run -d -p 8000:8000 -p 9000:9000 -p 9443:9443 --name=portainer --restart=always -v /run/user/1000/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest"
alias docker-restart="systemctl --user restart docker"
alias k='kubectl'
alias update-system="sudo apt update"
alias upgrade-system="sudo apt update && sudo apt upgrade -y"
alias apt-install="sudo apt install"
alias apt-remove="sudo apt remove"
alias ls="ls -ahl --color=auto"
alias ..="cd .."
alias mv="mv -i"
alias cp="cp -i"
alias rm="rm -i"
alias ln="ln -i"
alias upgrade-pyenv="cd $HOME/.pyenv && git pull && cd -"
alias clear-ipython-history="rm -f $HOME/.ipython/profile_default/history.sqlite"
alias edit-term-config="code $HOME/.config/wezterm/wezterm.lua"
