#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    aws_profile=$1
else
    aws_profile=$(aws configure list-profiles | fzf)
fi

if [[ -z "$aws_profile" ]]; then
    exit 0
fi

export AWS_PROFILE="$aws_profile"
