#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
preview_script="$script_dir/tmux-sessions-preview"

if [[ $# -eq 1 ]]; then
    session=$1
else
    if [ "$(uname)" = "Darwin" ]; then
        session=$(find "$HOME/.config" "$HOME/projects" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | \
            fzf --layout=reverse --border --preview "$preview_script {}" --preview-window=right:50%:wrap --header='Select a project directory')
    elif [ "$(uname)" = "Linux" ]; then
        session=$(find "$HOME/.config" "$HOME/work" "$HOME/private" "$HOME/projects" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | \
            fzf --layout=reverse --border --preview "$preview_script {}" --preview-window=right:50%:wrap --header='Select a project directory')
    fi
fi

if [[ -z "$session" ]]; then
    exit 0
fi

session_name=$(basename "$session" | tr '. ' '_' | tr -cd '[:alnum:]_-')
tmux_running=$(tmux list-sessions 2>/dev/null)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$session_name" -c "$session"
    exit 0
fi

if ! tmux has-session -t "$session_name" 2>/dev/null; then
    tmux new-session -s "$session_name" -c "$session" -d
fi

if [[ -z $TMUX ]] && [[ $tmux_running ]]; then
    tmux attach-session -t "$session_name"
else
    tmux switch-client -t "$session_name"
fi
